# Generated by Django 5.1.4 on 2025-02-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appt_file_name', models.CharField(max_length=255)),
                ('location_number', models.IntegerField()),
                ('location_name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('active_status', models.CharField(blank=True, max_length=50, null=True)),
                ('pelvic_health', models.CharField(blank=True, max_length=10, null=True)),
                ('training_haus', models.CharField(blank=True, max_length=10, null=True)),
                ('anytime_fitness', models.CharField(blank=True, max_length=10, null=True)),
                ('concussion', models.CharField(blank=True, max_length=10, null=True)),
                ('urgent_care', models.CharField(blank=True, max_length=10, null=True)),
                ('nutrition_center', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
