# Generated by Django 5.1.4 on 2025-02-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organized_location', '0002_alter_organizedlocation_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizedlocation',
            name='anytime_fitness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organizedlocation',
            name='concussion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organizedlocation',
            name='nutrition_center',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organizedlocation',
            name='pelvic_health',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organizedlocation',
            name='training_haus',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organizedlocation',
            name='urgent_care',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
